In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], 
             [4, 5 ,6],
             [7, 8, 9]])

b[1,1] = 10

print(a.shape)
print(b.shape)
print(a.dtype)
print(b)

(3,)
(3, 3)
int32
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


In [2]:
import numpy as np

persontype = np.dtype({
    "names": ["name", "age", "chinese", "math", "english"],
    "formats": ["S32", "i", "f", "f", "f"]})
peoples = np.array([("ZhangFei", 32, 75, 100, 90), ("GuangYu", 24, 85, 96, 88.5),
                    ("ZhaoYun", 28, 85, 92, 96.5), ("HuangZhong", 29, 65, 85, 100)],
                  dtype=persontype)

ages = peoples[:]["age"]
chineses = peoples[:]["chinese"]
maths = peoples[:]["math"]
englishs = peoples[:]["english"]
print(np.mean(ages))
print(np.mean(chineses))
print(np.mean(maths))
print(np.mean(englishs))

28.25
77.5
93.25
93.75


In [3]:
x1 = np.arange(1, 11, 2)
x2 = np.linspace(1, 9, 5)
print(x1, x2)

[1 3 5 7 9] [1. 3. 5. 7. 9.]


In [4]:
import numpy as np

a = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(np.amin(a))
print(np.amin(a, 0))
print(np.amin(a, 1))
print(np.amax(a))
print(np.amax(a, 0))
print(np.amax(a, 1))


1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [5]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.ptp(a))
print(np.ptp(a, 0))
np.ptp(a, 1)

8
[6 6 6]


array([2, 2, 2])

In [6]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.percentile(a, 50))
print(np.percentile(a, 50, axis=0))
print(np.percentile(a, 50, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [7]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.median(a))
print(np.median(a, 0))
print(np.median(a, 1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [8]:
print(np.mean(a))
print(np.mean(a, 0))
print(np.mean(a, 1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [9]:
a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
np.average(a)
np.average(a, weights=wts)

3.0

In [10]:
a = np.array([1,2,3,4])
print(np.std(a))
print(np.var(a))

1.118033988749895
1.25


In [11]:
a = np.array([[4,3,2],[2,4,1]])
np.sort(a)

array([[2, 3, 4],
       [1, 2, 4]])

In [12]:
np.sort(a, axis=None)

array([1, 2, 2, 3, 4, 4])

In [13]:
np.sort(a, axis=0)

array([[2, 3, 1],
       [4, 4, 2]])

In [14]:
np.sort(a, axis=1)

array([[2, 3, 4],
       [1, 2, 4]])

In [15]:
# 统计全班的成绩
import numpy as np

student_type = np.dtype({
    "names": ["name", "chinese", "math", "english"],
    "formats": ["S32", "f", "f", "f"]
})
students = np.array([("ZhangFei", 66, 65, 30), ("GuanYu", 95, 85, 98),
                     ("ZhaoYun", 93, 92, 96), ("HuangZhong", 90, 88, 77),
                     ("DianWei", 80, 90, 90)],
                    dtype=student_type)

chineses = students[:]["chinese"]
maths = students[:]["math"]
englishs = students[:]["english"]

def show(subject, mark):
    print("{} | {} | {} | {} | {} | {}".
          format(subject, np.mean(mark), np.amin(mark), np.amax(mark), np.std(mark), np.var(mark)))

print("科目 | 平均成绩 | 最低成绩 | 最高成绩 | 标准差 | 方差")
show("语文", chineses)
show("数学", maths)
show("英语", englishs)

ranking = sorted(students, key=lambda x:x[1]+x[2]+x[3], reverse=True)
print(ranking)

科目 | 平均成绩 | 最低成绩 | 最高成绩 | 标准差 | 方差
语文 | 84.80000305175781 | 66.0 | 95.0 | 10.721940040588379 | 114.96000671386719
数学 | 84.0 | 65.0 | 92.0 | 9.777524948120117 | 95.5999984741211
英语 | 78.19999694824219 | 30.0 | 98.0 | 25.190473556518555 | 634.5599365234375
[(b'ZhaoYun', 93., 92., 96.), (b'GuanYu', 95., 85., 98.), (b'DianWei', 80., 90., 90.), (b'HuangZhong', 90., 88., 77.), (b'ZhangFei', 66., 65., 30.)]


In [16]:
import pandas as pd

x1 = pd.Series([1,2,3,4])
x2 = pd.Series(index=["a", "b", "c", "d"],data=[1,2,3,4])

In [17]:
x1

0    1
1    2
2    3
3    4
dtype: int64

In [18]:
x2

a    1
b    2
c    3
d    4
dtype: int64

In [19]:
d = {"a": 1, "b": 2, "c": 3, "d":4}
x3 = pd.Series(d)
x3

a    1
b    2
c    3
d    4
dtype: int64

In [20]:
import pandas as pd

data = {"Chinese":[66, 95, 93, 90, 80], "Math":[30, 98, 96, 77, 90], "English":[65, 85, 92, 88, 90]}
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data, index=["ZhangFei", "GuanYu", "ZhaoYun", "HuangZhong", "DianWei"],
                   columns=["Chinese", "Math", "English"])
print(df1)
print(df2)

   Chinese  Math  English
0       66    30       65
1       95    98       85
2       93    96       92
3       90    77       88
4       80    90       90
            Chinese  Math  English
ZhangFei         66    30       65
GuanYu           95    98       85
ZhaoYun          93    96       92
HuangZhong       90    77       88
DianWei          80    90       90


In [21]:
import pandas as pd

data = {"Chinese":[66, 95, 93, 90, 80], "Math":[30, 98, 96, 77, 90], "English":[65, 85, 92, 88, 90]}
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data, index=["ZhangFei", "GuanYu", "ZhaoYun", "HuangZhong", "DianWei"],
                   columns=["Chinese", "Math", "English"])
print(df1)
print(df2)

   Chinese  Math  English
0       66    30       65
1       95    98       85
2       93    96       92
3       90    77       88
4       80    90       90
            Chinese  Math  English
ZhangFei         66    30       65
GuanYu           95    98       85
ZhaoYun          93    96       92
HuangZhong       90    77       88
DianWei          80    90       90


In [22]:
df = df2.drop(columns=["Chinese"])
df

Math  English
ZhangFei      30       65
GuanYu        98       85
ZhaoYun       96       92
HuangZhong    77       88
DianWei       90       90

In [23]:
df = df2.drop(index=["ZhangFei"])
df

Chinese  Math  English
GuanYu           95    98       85
ZhaoYun          93    96       92
HuangZhong       90    77       88
DianWei          80    90       90

In [24]:
df2.rename(columns={"Chinese":"YuWen", "Math":"ShuXue", "English":"YingYu"}, inplace=True)
df2

YuWen  ShuXue  YingYu
ZhangFei       66      30      65
GuanYu         95      98      85
ZhaoYun        93      96      92
HuangZhong     90      77      88
DianWei        80      90      90

In [25]:
df2.drop_duplicates()

YuWen  ShuXue  YingYu
ZhangFei       66      30      65
GuanYu         95      98      85
ZhaoYun        93      96      92
HuangZhong     90      77      88
DianWei        80      90      90

In [26]:
df2["YuWen"].astype('str')

ZhangFei      66
GuanYu        95
ZhaoYun       93
HuangZhong    90
DianWei       80
Name: YuWen, dtype: object

In [27]:
import numpy as np

df2["YuWen"].astype(np.int64)

ZhangFei      66
GuanYu        95
ZhaoYun       93
HuangZhong    90
DianWei       80
Name: YuWen, dtype: int64

In [28]:
df2["YuWen"].astype('str')

ZhangFei      66
GuanYu        95
ZhaoYun       93
HuangZhong    90
DianWei       80
Name: YuWen, dtype: object

In [29]:
df2

YuWen  ShuXue  YingYu
ZhangFei       66      30      65
GuanYu         95      98      85
ZhaoYun        93      96      92
HuangZhong     90      77      88
DianWei        80      90      90

In [30]:
df2

YuWen  ShuXue  YingYu
ZhangFei       66      30      65
GuanYu         95      98      85
ZhaoYun        93      96      92
HuangZhong     90      77      88
DianWei        80      90      90

In [31]:
df2["YuWen"].astype('str')

ZhangFei      66
GuanYu        95
ZhaoYun       93
HuangZhong    90
DianWei       80
Name: YuWen, dtype: object

In [32]:
import pandas as pd

data = {"Chinese":[' 66 ', ' 95$$$', ' 93 ',' 90 ', ' 80 '], "Math":[30, 98, 96, 77, 90], "English":[65, 85, 92, 88, 90]}
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data, index=["ZhangFei", "GuanYu", "ZhaoYun", "HuangZhong", "DianWei"],
                   columns=["Chinese", "Math", "English"])
df2

Chinese  Math  English
ZhangFei       66     30       65
GuanYu       95$$$    98       85
ZhaoYun        93     96       92
HuangZhong     90     77       88
DianWei        80     90       90

In [33]:
# 删除左右两边空格
df2['Chinese']=df2['Chinese'].map(str.strip)
# 删除左边空格
df2['Chinese']=df2['Chinese'].map(str.lstrip)
# 删除右边空格
df2['Chinese']=df2['Chinese'].map(str.rstrip)
df2['Chinese']=df2['Chinese'].str.strip('$')

In [34]:
df2

Chinese  Math  English
ZhangFei        66    30       65
GuanYu          95    98       85
ZhaoYun         93    96       92
HuangZhong      90    77       88
DianWei         80    90       90

In [39]:
import pandas as pd

data = {"Chinese":[66, 95, 93, 90, 80], "Math":[30, 98, 96, 77, 90], "English":[None, 85, 92, 88, 90]}
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data, index=["ZhangFei", "GuanYu", "ZhaoYun", "HuangZhong", "DianWei"],
                   columns=["Chinese", "Math", "English"])
df2

Chinese  Math  English
ZhangFei         66    30      NaN
GuanYu           95    98     85.0
ZhaoYun          93    96     92.0
HuangZhong       90    77     88.0
DianWei          80    90     90.0

In [36]:
df2.isnull()

Chinese   Math  English
ZhangFei      False  False     True
GuanYu        False  False    False
ZhaoYun       False  False    False
HuangZhong    False  False    False
DianWei       False  False    False

In [37]:
df2.isnull().any()

Chinese    False
Math       False
English     True
dtype: bool

In [40]:
import pandas as pd

data = {"Name":["ZhangFei", "GuanYu", "ZhaoYun", "HuangZhong", "DianWei"],
        "Chinese":[66, 95, 93, 90, 80], 
        "Math":[30, 98, 96, 77, 90], 
        "English":[None, 85, 92, 88, 90]}
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data,
                   columns=["Name", "Chinese", "Math", "English"])
df2

Name  Chinese  Math  English
0    ZhangFei       66    30      NaN
1      GuanYu       95    98     85.0
2     ZhaoYun       93    96     92.0
3  HuangZhong       90    77     88.0
4     DianWei       80    90     90.0

In [41]:
df2["Name"] = df2["Name"].apply(str.upper)

In [42]:
df2

Name  Chinese  Math  English
0    ZHANGFEI       66    30      NaN
1      GUANYU       95    98     85.0
2     ZHAOYUN       93    96     92.0
3  HUANGZHONG       90    77     88.0
4     DIANWEI       80    90     90.0

In [44]:
def double_df_chinese(x):
    return 2*x

df2["Chinese"] = (df2["Chinese"]).apply(double_df_chinese)

In [45]:
df2

Name  Chinese  Math  English
0    ZHANGFEI      132    30      NaN
1      GUANYU      190    98     85.0
2     ZHAOYUN      186    96     92.0
3  HUANGZHONG      180    77     88.0
4     DIANWEI      160    90     90.0

In [48]:
def plus(df, n, m):
    df["new1"] = (df["Chinese"] + df["English"]) * m
    df["new2"] = (df["Chinese"] + df["English"]) * n
    return df

df2 = df2.apply(plus, axis=1, args=(2, 3))

In [49]:
df2

Name  Chinese  Math  English   new1   new2
0    ZHANGFEI      132    30      NaN    NaN    NaN
1      GUANYU      190    98     85.0  825.0  550.0
2     ZHAOYUN      186    96     92.0  834.0  556.0
3  HUANGZHONG      180    77     88.0  804.0  536.0
4     DIANWEI      160    90     90.0  750.0  500.0

In [51]:
df1 = pd.DataFrame({"name":["ZhangFei", "GuanYu", "a", "b", "c"], "data1": range(5)})
df1

name  data1
0  ZhangFei      0
1    GuanYu      1
2         a      2
3         b      3
4         c      4

In [52]:
df1.describe()

data1
count  5.000000
mean   2.000000
std    1.581139
min    0.000000
25%    1.000000
50%    2.000000
75%    3.000000
max    4.000000

In [54]:
df1 = pd.DataFrame({"name":["ZhangFei", "GuanYu", "a", "b", "c"], "data1": range(5)})
df2 = pd.DataFrame({"name":["ZhangFei", "GuanYu", "A", "B", "C"], "data2": range(5)})

In [55]:
df1

name  data1
0  ZhangFei      0
1    GuanYu      1
2         a      2
3         b      3
4         c      4

In [56]:
df2

name  data2
0  ZhangFei      0
1    GuanYu      1
2         A      2
3         B      3
4         C      4

In [57]:
df3 = pd.merge(df1, df2, on="name")

In [58]:
df3

name  data1  data2
0  ZhangFei      0      0
1    GuanYu      1      1

In [59]:
df3 = pd.merge(df1, df2, how="inner")

In [60]:
df3

name  data1  data2
0  ZhangFei      0      0
1    GuanYu      1      1

In [61]:
df3 = pd.merge(df1, df2, how="left")

In [62]:
df3

name  data1  data2
0  ZhangFei      0    0.0
1    GuanYu      1    1.0
2         a      2    NaN
3         b      3    NaN
4         c      4    NaN

In [63]:
df3 = pd.merge(df1, df2, how="right")

In [64]:
df3

name  data1  data2
0  ZhangFei    0.0      0
1    GuanYu    1.0      1
2         A    NaN      2
3         B    NaN      3
4         C    NaN      4

In [66]:
df3 = pd.merge(df1, df2, how="outer")

In [67]:
df3

name  data1  data2
0  ZhangFei    0.0    0.0
1    GuanYu    1.0    1.0
2         a    2.0    NaN
3         b    3.0    NaN
4         c    4.0    NaN
5         A    NaN    2.0
6         B    NaN    3.0
7         C    NaN    4.0

In [94]:
import pandas as pd

data = {"name": ["张飞", "关羽", "赵云", "黄忠", "典韦", "典韦"],
        "chinese": [66, 95, 95, 90, 80, 80],
        "english": [65, 85, 92, 88, 90, 90],
        "math": [None, 98, 96, 77, 90, 90]}

grade_df = pd.DataFrame(data, columns=["name", "chinese", "english", "math"])

# 去除重复行
grade_df = grade_df.drop_duplicates()

# 重命列名
grade_df.rename(columns={"name":"姓名", "chinese":"语文", "english":"英语", "math":"数学"}, inplace=True)

# 用数学成绩平均值填充张飞数学成绩缺失值
math_mean = grade_df["数学"].mean()
grade_df = grade_df.fillna(math_mean)

grade_df["总成绩"] = grade_df.sum(axis=1)

In [95]:
grade_df

姓名  语文  英语     数学     总成绩
0  张飞  66  65  90.25  221.25
1  关羽  95  85  98.00  278.00
2  赵云  95  92  96.00  283.00
3  黄忠  90  88  77.00  255.00
4  典韦  80  90  90.00  260.00