In [1]:
from sklearn import preprocessing
import numpy as np


# 初始化数据，每一行代表一个样本，每一列代表一个特征
x = np.array([[0., -3., 1.],
              [3., 1., 2.],
              [0., 1., -1.]])

# 将数据 [0,1] 规范化
min_max_scaler = preprocessing.MinMaxScaler()
minmax_x = min_max_scaler.fit_transform(x)
print(minmax_x)

D:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
D:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


[[0.         0.         0.66666667]
 [1.         1.         1.        ]
 [0.         1.         0.        ]]


In [2]:
from sklearn import preprocessing
import numpy as np


# 初始化数据，每一行代表一个样本，每一列代表一个特征
x = np.array([[0., -3., 1.],
              [3., 1., 2.],
              [0., 1., -1.]])

# 将数据 Z-Score 规范化
scaled_x = preprocessing.scale(x)
print(scaled_x)

[[-0.70710678 -1.41421356  0.26726124]
 [ 1.41421356  0.70710678  1.06904497]
 [-0.70710678  0.70710678 -1.33630621]]


In [3]:
from sklearn import preprocessing
import numpy as np


# 初始化数据，每一行代表一个样本，每一列代表一个特征
x = np.array([[0., -3., 1.],
              [3., 1., 2.],
              [0., 1., -1.]])

# 小数定标规范化
j = np.ceil(np.log10(np.max(abs(x))))
scaled_x = x / (10**j)
print(scaled_x)

[[ 0.  -0.3  0.1]
 [ 0.3  0.1  0.2]
 [ 0.   0.1 -0.1]]


In [5]:
from sklearn import preprocessing
import numpy as np


# 初始化数据，每一行代表一个样本，每一列代表一个特征
x = np.array([[5000], 
              [16000], 
              [58000]])

min_max_scaler = preprocessing.MinMaxScaler()
minmax_x = min_max_scaler.fit_transform(x)
print(minmax_x)

[[0.        ]
 [0.20754717]
 [1.        ]]


D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
